### ISSUE TITLE
Since update of Firefox 37.0.2  Emoji Cheatsheet causes other "No Restart" add-ons to go AWAL

### ISSUE THREAD

**Issue by mrbunnylamakins** [johannhof/emoji-helper#40]
Since update of Firefox 37.0.2 Emoji Cheatsheet causes other "No Restart" add-ons to go AWAL

Took me over a hour and Next day before I figured out that your Add-on is causing the other "No Restart" icons on toolbar/ add-on bar to vanish. When the Emoji Cheatsheet is not showing on toolbar so isn't the other "No Restart". When I disable Emoji Cheatsheet everything works fine then. 

it was working fine on Firefox 37.0.1

![screenshot_162a](https://cloud.githubusercontent.com/assets/12091459/7309487/0ac3d9ae-e9ed-11e4-9fa9-f3a6769adb4e.png)

**Comment by mikhoul** [comment]
Tried under Firefox V39.xx under Win 7 and everything is fine.

**Comment by johannhof** [comment]
Hey, since the button SDK is quite straightforward it's hard to imagine that we're causing this. It sounds like a bug in Firefox that could be related to a broken profile.

You might want to try to repair your profile by [refreshing Firefox](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings) __This will remove your addons__

I'd also suggest trying to [create a new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles)

**Comment by mrbunnylamakins** [comment]
It was working fine under 37.0.1 and I am not abut to reload over 200 add-ons for one add-on. I also works if I disable and enable it. .... Fact also they said things work different for Firefox under Windows 8/8.1 like flash.

**Comment by johannhof** [comment]
It's a WebExtension now, either the problem doesn't exist anymore or it's out of my control.
