### ISSUE TITLE
Won't turn on in Firefox private mode

### ISSUE THREAD

**Issue by k4mu** [johannhof/emoji-helper#45]
If you start the browser in private mode, instead of normal mode, the add-on does not show up on the menu bar and there is no way to get to it.

**Comment by jackunion** [comment]
https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/private-browsing

This should do the trick.
And more than that: they've deprecated *cfx* in favor of the new *jpm* tool, so *package.json* needs some more improvements in order to work fine with it.

**Comment by jackunion** [comment]
The *package.json* for firefox should contain these lines to work with jpm:

```"main": "lib/main.js"``` (instead of just "main": "main")
```"id": "jid1-Xo5SuA6qc1DFpw@jetpack"``` (@jetpack at the end)
```"permissions": {"private-browsing": true}``` (to turn the add-on in private windows)

I'm not sure if there is a way to overwrite specific lines with gulp, so a separate *package.json* is probably the right way to deal with this.

**Comment by jackunion** [comment]
@johannhof

**Comment by rugk** [comment]
As https://github.com/johannhof/emoji-helper/issues/59 was merged this issue can be closed AFAIK.

**Comment by jackunion** [comment]
@rugk it didn't fix this issues, I just wanted @johannhof totake a look at some ideas I had.

**Comment by rugk** [comment]
Okay.

**Comment by johannhof** [comment]
We generally need to switch to JPM, then we fix this. See bug #65
